### ISSUE TITLE
singbox 内核 ignore_client_bandwidth 设置不生效

### ISSUE THREAD

**Issue by 95289527** [wyx2685/V2bX#47]
**描述该错误**
简单地描述一下这个bug是什么

singbox内核设置 ignore_client_bandwidth  不生效

v2bx 版本 0.1.5

面板版本 xboard 1.0.0 

面板节点设置

![Image](https://github.com/user-attachments/assets/aa4ffc9d-4572-4a54-81fb-1edace57f5ce)

根据singbox文档 [https://sing-box.sagernet.org/zh/configuration/inbound/hysteria2/#ignore_client_bandwidth](https://sing-box.sagernet.org/zh/configuration/inbound/hysteria2/#ignore_client_bandwidth)

服务端设置了ignore_client_bandwidth ，没有设置带宽会始终使用bbr，客户端带宽设置会不生效。

但是使用v2bx服务端用以上配置，v2rayn将带宽设置为10Mbits测速会只有10Mbits，设置为1000Mbits会跑的快很多。客户端设置任然有效

用singbox原生的服务端设置ignore_client_bandwidth为true时，无论v2rayn带宽设置为多少都可以跑出很高的速度，客户端设置没有生效

**复现**
请自行复现，并贴出详细步骤操作过程

config.json 配置文件
```
cat /etc/V2bX/config.json

{
    "Log": {
        "Level": "debug",
        "Output": "/etc/V2bX/v2bx.log"
    },
    "Cores": [
    {
        "Type": "sing",
        "Log": {
            "Level": "debug",
	    "Output": "/etc/V2bX/singbox.log",
            "Timestamp": true
        },
        "NTP": {
            "Enable": false,
            "Server": "time.apple.com",
            "ServerPort": 0
        },
        "OriginalPath": "/etc/V2bX/sing_origin.json",
	"EnableConnClear": true
    }],
    "Nodes": [{
            "Core": "sing",
            "ApiHost": "https://somesite",
            "ApiKey": "somekey",
            "NodeID": 1,
            "NodeType": "hysteria2",
	    "Hysteria2ConfigPath": "/etc/V2bX/hy2config.yaml",
            "Timeout": 30,
            "ListenIP": "0.0.0.0",
            "SendIP": "0.0.0.0",
            "DeviceOnlineMinTraffic": 1000,
            "TCPFastOpen": true,
            "SniffEnabled": true,
            "EnableDNS": true,
            "CertConfig": {
                "CertMode": "self",
                "RejectUnknownSni": false,
                "CertDomain": "amazon.com",
                "CertFile": "/etc/V2bX/fullchain.cer",
                "KeyFile": "/etc/V2bX/cert.key",
                "Email": "v2bx@github.com",
                "Provider": "cloudflare",
                "DNSEnv": {
                    "EnvName": "env1"
                }
            }
        }



]
}
```

hy2config 配置文件
```
cat /etc/V2bX/hy2config.yaml 

quic:
  initStreamReceiveWindow: 8388608
  maxStreamReceiveWindow: 8388608
  initConnReceiveWindow: 20971520
  maxConnReceiveWindow: 20971520
  maxIdleTimeout: 300s
  maxIncomingStreams: 65535
  disablePathMTUDiscovery: false
ignoreClientBandwidth: true
disableUDP: false
udpIdleTimeout: 60s
resolver:
  type: system
acl:
  inline:
    - direct(geosite:google)
    - block(geosite:cn)
    - block(geoip:cn)
masquerade:
  type: 404
brutal_debug: true
```

**日志和错误**
请使用`v2bx log`查看并添加日志，没有日志的issue不会得到答复并且会被直接关闭
```
tail -f /etc/V2bX/v2bx.log 

time="2025-02-08T05:50:43+08:00" level=info msg="Report 1 users traffic" tag="[https://somesite]-hysteria2:1"
time="2025-02-08T05:50:43+08:00" level=info msg="Total 1 online users, 0 Reported" tag="[https://somesite]-hysteria2:1"
time="2025-02-08T05:53:29+08:00" level=debug msg="Clear online ip..." Type=Limiter
time="2025-02-08T05:53:29+08:00" level=debug msg="Clear online ip done" Type=Limiter
time="2025-02-08T05:56:29+08:00" level=debug msg="Clear online ip..." Type=Limiter
time="2025-02-08T05:56:29+08:00" level=debug msg="Clear online ip done" Type=Limiter
time="2025-02-08T05:59:29+08:00" level=debug msg="Clear online ip..." Type=Limiter
time="2025-02-08T05:59:29+08:00" level=debug msg="Clear online ip done" Type=Limiter
time="2025-02-08T06:02:29+08:00" level=debug msg="Clear online ip..." Type=Limiter
time="2025-02-08T06:02:29+08:00" level=debug msg="Clear online ip done" Type=Limiter
time="2025-02-08T06:05:29+08:00" level=debug msg="Clear online ip..." Type=Limiter
time="2025-02-08T06:05:29+08:00" level=debug msg="Clear online ip done" Type=Limiter
```

**额外的内容**
在这里添加关于问题的任何其他内容
