### ISSUE TITLE
Xray ws path problem 

### ISSUE THREAD

**Issue by mahdisharbaf** [wyx2685/V2bX#5]
When I define a path on the server side in the Xray core for VMess WS connections, it is not applied in the connection.

**Comment by PA733** [comment]
Same here.

**Comment by wyx2685** [comment]
@PA733 no detail = no solve

**Comment by PA733** [comment]
> @PA733 no detail = no solve

抱歉，以为这个很好复现，所以没想着补充信息。
晚点看看怎么补充。

**Comment by PA733** [comment]
# 环境
Xboard [f099cf6](https://github.com/users/cedar2025/packages/container/xboard/229753270?tag=f099cf6)
V2bX [v0.0.8-20240624](https://github.com/wyx2685/V2bX/releases/tag/v0.0.8-20240624)
Clash Verge Rev [v1.6.6](https://github.com/clash-verge-rev/clash-verge-rev/releases/tag/v1.6.6)

# 复现方法

1. 创建一个 Vmess 节点，传输类型 WebSocket
2. 协议配置修改为
```json
{
  "path": "/test?ed=2048",
  "headers": {
    "Host": "test.v-50.me"
  }
}
```
![image](https://github.com/wyx2685/V2bX/assets/67588574/828bb831-cd27-4a35-8765-d812b0d3aa65)

3. 客户端尝试连接
```yaml
{
    name: "🇭🇰 [Vmess]v-50 Test",
    server: test.v-50.me,
    port: 80,
    type: vmess,
    uuid: c625824c-4da6-48c0-8c67-a972a7809d83,
    alterId: 0,
    cipher: auto,
    tls: false,
    network: ws,
    ws-opts: { path: "/test?ed=2048", headers: { Host: test.v-50.me } },
    udp: true,
}
```
![image](https://github.com/wyx2685/V2bX/assets/67588574/4dfed858-ef86-44f7-9d89-966a61f0b861)
此时尝试 curl 一下：
![image](https://github.com/wyx2685/V2bX/assets/67588574/152bbc57-97be-418b-9308-1b79b2fa60b1)
可见，根目录是可以访问到的，但 /test 报 404
4. 修改客户端配置（但不修改 Xboard 上的配置）：将 ws-opt -> path 中的 `test` 去掉
```yaml
ws-opts: { path: "/?ed=2048", headers: { Host: test.v-50.me } }
```
![image](https://github.com/wyx2685/V2bX/assets/67588574/68f76104-c498-4369-b2ac-842343903c2b)
连接恢复正常。

# 总结
至少在我的环境上，V2bX 不会正常应用 path 配置（看上去好像是把 Path 丢掉了，因为 ?ed=2048 带来的 0-RTT 还是生效的）。

**Comment by PA733** [comment]
# 环境
Xboard [f099cf6](https://github.com/users/cedar2025/packages/container/xboard/229753270?tag=f099cf6)
V2bX [v0.0.8-20240624](https://github.com/wyx2685/V2bX/releases/tag/v0.0.8-20240624)
Clash Verge Rev [v1.6.6](https://github.com/clash-verge-rev/clash-verge-rev/releases/tag/v1.6.6)

# 复现方法

1. 创建一个 Vmess 节点，传输类型 WebSocket
2. 协议配置修改为
```json
{
  "path": "/test?ed=2048",
  "headers": {
    "Host": "test.v-50.me"
  }
}
```
![image](https://github.com/wyx2685/V2bX/assets/67588574/828bb831-cd27-4a35-8765-d812b0d3aa65)

3. 客户端尝试连接
```yaml
{
    name: "🇭🇰 [Vmess]v-50 Test",
    server: test.v-50.me,
    port: 80,
    type: vmess,
    uuid: 45de11df-6767-46f8-b5f8-0cf72e0154db,
    alterId: 0,
    cipher: auto,
    tls: false,
    network: ws,
    ws-opts: { path: "/test?ed=2048", headers: { Host: test.v-50.me } },
    udp: true,
}
```
![image](https://github.com/wyx2685/V2bX/assets/67588574/4dfed858-ef86-44f7-9d89-966a61f0b861)
此时尝试 curl 一下：
![image](https://github.com/wyx2685/V2bX/assets/67588574/152bbc57-97be-418b-9308-1b79b2fa60b1)
可见，根目录是可以访问到的，但 /test 报 404
4. 修改客户端配置（但不修改 Xboard 上的配置）：将 ws-opt -> path 中的 `test` 去掉
```yaml
ws-opts: { path: "/?ed=2048", headers: { Host: test.v-50.me } }
```
![image](https://github.com/wyx2685/V2bX/assets/67588574/68f76104-c498-4369-b2ac-842343903c2b)
连接恢复正常。

# 总结
至少在我的环境上，V2bX 不会正常应用 path 配置（看上去好像是把 Path 丢掉了，因为 `?ed=2048` 带来的 0-RTT 还是生效的）。
