### ISSUE TITLE
无法设置realityconfigs

### ISSUE THREAD

**Issue by Finer3004** [wyx2685/V2bX#50]
以前的XrayR有RealityConfigs实现定制回落
```
      REALITYConfigs:
        Show: false # Show REALITY debug
        Dest: ${portfallback} # Required, Same as fallback
        ProxyProtocolVer: 2 # Send PROXY protocol version, 0 for disable
        ServerNames: # Required, list of available serverNames for the client, * wildcard is not supported at the moment.
          - ${domain}
        PrivateKey: # 可不填
        MinClientVer: # Optional, minimum version of Xray client, format is x.y.z.
        MaxClientVer: # Optional, maximum version of Xray client, format is x.y.z.
        MaxTimeDiff: 0 # Optional, maximum allowed time difference, unit is in milliseconds.
        ShortIds: # 可不填
          - ""
```
V2bX似乎没有办法设置,只能从面板读取.我想回落到本地端口,不对外暴露,不知道能实现吗?感谢
